__all__ = ['country_mapping_dict', 'country_selection_menu_dict', 'flirt_mapping_dict']

country_mapping_dict = {
    "nl": ["netherlands", "nederland", "nl", "netherland", "nderland", "nederlandnl", "nedrland", "nederlan", "nederlnd"],
    "an": ["nederlandse antillen", "netherlands antilles"],
    "de": ["germany", "deutschland", "duitsland", "de", "brd"],
    "be": ["belgium", "belgië", "belgie"],
    "us": ["usa", "us", "united states", "verenigde staten", "united states of america", "u s a", "vs"],
    "gb": ["united kingdom", "gb", "great britain", "groot brittannie", "groot-brittannië", "uk", "u k",
           "verenigd koninkrijk", "grat britain", "united kongdom", "groot brittannië", "england", "scotland", "northern ireland"],
    "ch": ["switzerland", "ch", "zwitserland", "switserland", "swiss", "swizterland"],
    "fr": ["france", "fr", "frankrijk"],
    "es": ["spain", "es", "spanje", "mallorca"],
    "ru": ["russia", "ru", "rusland"],
    "ca": ["canada", "ca", "british columbia"],
    "ne": ["ne"],
    "au": ["australia", "au", "australië", "australie"],
    "it": ["italy", "it", "italie", "italië"],
    "jp": ["japan", "jp"],
    "il": ["israel", "il", "israël"],
    "at": ["austria", "at", "oostenrijk", "austrria"],
    "no": ["norway", "no", "noorwegen"],
    "se": ["sweden", "se", "zweden"],
    "fi": ["finland", "fi"],
    "dk": ["denmark", "dk", "denemarken"],
    "br": ["brazil", "br", "brasil", "brazilie", "brazilië", "brasilia"],
    "pt": ["portugal", "pt"],
    "ie": ["ireland", "ie", "ierland"],
    "pl": ["poland", "pl", "polen"],
    "gr": ["greece", "gr", "griekenland"],
    "za": ["south africa", "za", "zuid afrika", "zuid-afrika"],
    "lu": ["luxembourg", "lu", "luxemburg"],
    "hk": ["hong kong", "hongkong"],
    "ee": ["estonia", "ee", "estland"],
    "mx": ["mexico", "mx"],
    "tr": ["turkey", "tr", "turkiye", "turkije"],
    "lv": ["latvia", "lv", "letland", "lavia", "lativia"],
    "ro": ["romania", "ro"],
    "kr": ["south korea", "kr", "korea", "zuid korea", "republic of korea", "skorea"],
    "sg": ["singapore", "sg"],
    "ua": ["ukraine", "ua"],
    "tw": ["taiwan"],
    "hu": ["hungary", "hu", "hongarije"],
    "nz": ["new zealand", "nz"],
    "lt": ["lithuania", "lt", "litouwen", "lithaunia"],
    "ar": ["argentina", "argentine"],
    "cz": ["czech republic", "cz", "czechia", "cezchia"],
    "cy": ["cyprus"],
    "ve": ["venezuela"],
    "sk": ["slovakia", "sk"],
    "is": ["iceland", "ijsland"],
    "cn": ["china", "china, people's republic of"],
    "kw": ["kuwait"],
    "sa": ["saudi arabia", "saudi arabië", "saudia arabia", "saudi-arabië"],
    "bg": ["bulgaria", "bulgarije", "bulgary"],
    "hr": ["croatia", "kroatië"],
    "in": ["india"],
    "cl": ["chile"],
    "ae": ["united arab emirates", "ae", "uae", "dubai"],
    "lb": ["lebanon", "libanon"],
    "co": ["colombia"],
    "si": ["slovenia", "si", "slovenië"],
    "pa": ["panama"],
    "mt": ["malta"],
    "th": ["thailand"],
    "my": ["malaysia"],
    "by": ["belarus"],
    "am": ["armenia"],
    "ge": ["georgia", "georgië"],
    "id": ["indonesia", "indonesie"],
    "ph": ["philippines", "filipijnen"],
    "rs": ["serbia"],
    "mc": ["monaco"],
    "pe": ["peru"],
    "qa": ["qatar"],
    "pr": ["puerto rico"],
    "al": ["albania"],
    "dz": ["algerije"],
    "eg": ["egypt", "egypte"],
    "uz": ["uzbekistan"],
    "az": ["azerbaijan", "azerbaidzjan"],
    "aw": ["aruba"],
    "sm": ["san marino"],
    "li": ["liechtenstein"],
    "sr": ["surinam", "suriname"],
    "lk": ["sri lanka"],
    "bb": ["barbados"],
    "uy": ["uruguay"],
    "ec": ["ecuador"],
    "kz": ["kazakhstan", "kazachstan", "kazahstan"],
    "ke": ["kenya"],
    "jm": ["jamaica"],
    "kh": ["cambodia"],
    "pk": ["pakistan"],
    "jo": ["jordan"],
    "gh": ["ghana"],
    "ma": ["morocco"],
    "gt": ["guatemala"],
    "cw": ["curacao", "curaçao"],
    "ug": ["uganda"],
    "tt": ["trinidad and tobago"],
    "vg": ["british virgin islands"],
    "bm": ["bermuda"],
    "bz": ["belize"],
    "ir": ["iran"],
    "ba": ["bosnia herzegowina"],
    "as": ["american samoa"],
    "af": ["afghanistan"],
    "ng": ["nigeria"],
    "iq": ["iraq"],
    "md": ["moldavia"],
    "sv": ["el salvador"],
    "zw": ["zimbabwe"],
    "me": ["montenegro"],
    "vi": ["usvi"],
    "mo": ["macau"],
    "hn": ["honduras"],
    "so": ["somalia"],
    "ky": ["cayman islands"],
    "je": ["channel islands"],
    "do": ["dominican republic"],
    "bh": ["bahrain"],
    "na": ["namibia"],
    "mq": ["martinique"],
    "vn": ["vietnam"],
    "bo": ["bolivia"],
    "mk": ["north macedonia", "noord-macedonië"],
    "om": ["oman"],
    "py": ["paraguay"],
}

country_selectio_menu_dict = [
    "nl", "au", "at", "be", "ca", "cz", "dk", "ee", "fi", "fr", "de", "gb", "gr", "hu",
    "ie", "il", "it", "jp", "kr", "lv", "lt", "lu", "mx", "nz", "no", "pl", "pt", "ro",
    "ru", "sg", "sk", "si", "za", "es", "se", "ch", "tr", "ua", "us", "br", "ae"
    ]

flirt_mapping_dict = {
    'flirtxl - messa da requiem': '22/23 messa da requiem flirt',
    'flirt xl - forsythe': '22/23 forsythe flirt',
    '23/24 operaflirt xl - don giovanni': '21/22 don giovanni flirt',
    '18/19 die zauberflote - operaflirt xl': '18/19 die zauberflote flirt',
    '23/24 flirt xl -  die zauberflote': '23/24 die zauberflote flirt',
    '23/24 flirt xl - frida': '23/24 frida flirt',
    '19/20 opera flirt xl cosi fan tutte': '19/20 cosi fan tutte flirt',
    '24/25 don quichot - flirt': '24/25 don quichot flirt' 
}

hh_replace_dict = {
    'beek (l.)': 'beek',
    'groningen (gemeente)': 'groningen',
    'hengelo (o.)': 'hengelo',
    'laren (nh.)': 'laren',
    "'s-gravenhage (gemeente)": 'den haag',
    'middelburg (z.)': 'middelburg',
    'rijswijk (zh.)': 'rijswijk',
    'stein (l.)': 'stein',
    'utrecht (gemeente)': 'utrecht'
}

nonvisitor_ids = [
    '0037q00000d5gxkqar',
    '0037q00000d5gxlqar',
    '0037q00000d5johqab',
    '0037q000007cqjkqa0',
    '0037q000007lgwlqa4',
    '0037q00000d5tlwqaz',
    '0037q00000boorlqa5',
    '0037q00000bnnfiqat',
    '0037q00000cmwoyqa0',
    '0037q00000boj2xqah',
    '0037q000007cxowqao',
    '0037q00000bnidzqap',
    '0037q00000boob7qap',
    '0037q00000d5johqab',
    '0037q00000boorsqap',
    '0037q00000kgdkzqav',
    '0037q00000boossqa5',
    '0037q00000d5zabqa3',
    '0037q00000boormqa5',
    '0037q00000booxsqa5',
    '0037q00000bool8qap',
    '0037q00000dmjviqa1',
    '0037q00000kgdwpqaf'
]

country_codes_income_dict = {
    'India': 'IN',
    'China': 'CN',
    'United States': 'US',
    'Indonesia': 'ID',
    'Pakistan': 'PK',
    'Nigeria': 'NG',
    'Brazil': 'BR',
    'Bangladesh': 'BD',
    'Russia': 'RU',
    'Ethiopia': 'ET',
    'Mexico': 'MX',
    'Japan': 'JP',
    'Egypt': 'EG',
    'Philippines': 'PH',
    'DR Congo': 'CD',
    'Vietnam': 'VN',
    'Iran': 'IR',
    'Turkey': 'TR',
    'Germany': 'DE',
    'Thailand': 'TH',
    'United Kingdom': 'GB',
    'Tanzania': 'TZ',
    'France': 'FR',
    'South Africa': 'ZA',
    'Italy': 'IT',
    'Kenya': 'KE',
    'Myanmar': 'MM',
    'Colombia': 'CO',
    'South Korea': 'KR',
    'Sudan': 'SD',
    'Uganda': 'UG',
    'Spain': 'ES',
    'Algeria': 'DZ',
    'Iraq': 'IQ',
    'Argentina': 'AR',
    'Yemen': 'YE',
    'Canada': 'CA',
    'Poland': 'PL',
    'Morocco': 'MA',
    'Angola': 'AO',
    'Ukraine': 'UA',
    'Uzbekistan': 'UZ',
    'Malaysia': 'MY',
    'Mozambique': 'MZ',
    'Ghana': 'GH',
    'Peru': 'PE',
    'Madagascar': 'MG',
    'Ivory Coast': 'CI',
    'Nepal': 'NP',
    'Cameroon': 'CM',
    'Venezuela': 'VE',
    'Niger': 'NE',
    'Australia': 'AU',
    'Syria': 'SY',
    'Mali': 'ML',
    'Burkina Faso': 'BF',
    'Taiwan': 'TW',
    'Sri Lanka': 'LK',
    'Malawi': 'MW',
    'Zambia': 'ZM',
    'Kazakhstan': 'KZ',
    'Chad': 'TD',
    'Chile': 'CL',
    'Romania': 'RO',
    'Senegal': 'SN',
    'Guatemala': 'GT',
    'Netherlands': 'NL',
    'Ecuador': 'EC',
    'Zimbabwe': 'ZW',
    'Guinea': 'GN',
    'Benin': 'BJ',
    'Rwanda': 'RW',
    'Burundi': 'BI',
    'Bolivia': 'BO',
    'Tunisia': 'TN',
    'South Sudan': 'SS',
    'Haiti': 'HT',
    'Belgium': 'BE',
    'Jordan': 'JO',
    'Dominican Republic': 'DO',
    'United Arab Emirates': 'AE',
    'Honduras': 'HN',
    'Czech Republic': 'CZ',
    'Sweden': 'SE',
    'Tajikistan': 'TJ',
    'Papua New Guinea': 'PG',
    'Portugal': 'PT',
    'Azerbaijan': 'AZ',
    'Greece': 'GR',
    'Hungary': 'HU',
    'Togo': 'TG',
    'Israel': 'IL',
    'Austria': 'AT',
    'Belarus': 'BY',
    'Switzerland': 'CH',
    'Sierra Leone': 'SL',
    'Laos': 'LA',
    'Turkmenistan': 'TM',
    'Kyrgyzstan': 'KG',
    'Paraguay': 'PY',
    'Nicaragua': 'NI',
    'Bulgaria': 'BG',
    'Serbia': 'RS',
    'El Salvador': 'SV',
    'Republic of the Congo': 'CG',
    'Denmark': 'DK',
    'Lebanon': 'LB',
    'Finland': 'FI',
    'Liberia': 'LR',
    'Norway': 'NO',
    'Slovakia': 'SK',
    'Palestine': 'Not Found',
    'Central African Republic': 'CF',
    'Ireland': 'IE',
    'Mauritania': 'MR',
    'Costa Rica': 'CR',
    'Panama': 'PA',
    'Croatia': 'HR',
    'Georgia': 'GE',
    'Mongolia': 'MN',
    'Uruguay': 'UY',
    'Bosnia and Herzegovina': 'BA',
    'Moldova': 'MD',
    'Namibia': 'NA',
    'Armenia': 'AM',
    'Lithuania': 'LT',
    'Jamaica': 'JM',
    'Albania': 'AL',
    'Gambia': 'GM',
    'Gabon': 'GA',
    'Botswana': 'BW',
    'Lesotho': 'LS',
    'Guinea-Bissau': 'GW',
    'Slovenia': 'SI',
    'Latvia': 'LV',
    'North Macedonia': 'MK',
    'Trinidad and Tobago': 'TT',
    'Timor-Leste': 'TL',
    'Estonia': 'EE',
    'Cyprus': 'CY',
    'Mauritius': 'MU',
    'Eswatini': 'SZ',
    'Djibouti': 'DJ',
    'Fiji': 'FJ',
    'Comoros': 'KM',
    'Guyana': 'GY',
    'Solomon Islands': 'SB',
    'Bhutan': 'BT',
    'Luxembourg': 'LU',
    'Montenegro': 'ME',
    'Suriname': 'SR',
    'Malta': 'MT',
    'Maldives': 'MV',
    'Cape Verde': 'CV',
    'Belize': 'BZ',
    'Iceland': 'IS',
    'Vanuatu': 'VU',
    'Sao Tome and Principe': 'ST',
    'Samoa': 'WS',
    'Saint Lucia': 'LC',
    'Kiribati': 'KI',
    'Seychelles': 'SC',
    'Micronesia': 'FM',
    'Tonga': 'TO',
    'Tuvalu': 'TV'
}

ticket_category_mapping_dict = {
    "regular": ["standaard", "kassa standaard"],
    "migration": ["migratie overig"],
    "student": ["student", "cjp", "kassa student", "kassa cjp", "epp studentenkorting", "studenten uva", 
                "uva geesteswetenschappen", "uva", "studievereniging"],
    "stadspas": ["stadspas", "stadspasactie", "kassa stadspas"],
    "group_discount": ["groep -10%", "groep -5%"],
    "youth_35": ["jongeren t/m 35 jaar", "off jongeren t/m 35 jaar", "kassa off jongeren tm 35 jaar", "off combi", "off collab",
                 "mm&m 50%", "mm&m 75%", "mm&m 75% - intro", "mm&m 50% - intro", "mm&m sprint 50%", "mm&m 25%", 
                "mm&m sprint 75%", "mm&m 25% - intro", "mm&m sprint 25%", "ypc35", "ypc30", "ypc25", "ypc"],
    "youth_16": ["jeugdkorting t/m 16 jaar", "kassa jeugdkorting"],
    "artform_discount": ["reductie dno", "reductie hnb", "tell a friend"],
    "special_discount": ["relatiekorting", "medewerker houthoff", "participant", "cultuur werkt", "moat", "ing",
                         "barter", "milieudefensie", "partner", "participanten voordeel", "amateur dansscholen",
                         "rode kruis", "participant vrijkaart", "nba", "relaties houthoff", "blindentolk",
                         "balletschool", "opera europa", "belcanto koren", "sponsoring", "ndt", "kunstscholen",
                         "erwin olaf", "amnesty", "plantage", "de balie", "amsterdam marketing", "arts & auto glossy",
                         "ladies eye", "lorenzonen", "ntr", "in the future", "wagner vereniging", "kco",
                         "cameraplaatsen", "ziekenhuizen", "zorgmedewerker", "business lounge", "breukvlakken",
                         "uitmarkt", "vriendenloterij", "we are public", "nieuwsbrief 20/21", "holland festival actie", 
                       "iamsterdam", "entree", "troostprijs", "steef de jong", "winactie", "changement", 
                       "podcast mm & aaf", "jump", "cjp winactie", "missie klassiek", "nieuwsbrief"],

}