__all__ = ['country_mapping_dict', 'country_selectio_menu_dict', 'flirt_mapping_dict']

country_mapping_dict = {
    "nl": ["netherlands", "nederland", "nl", "netherland", "nderland", "nederlandnl", "nedrland", "nederlan", "nederlnd"],
    "an": ["nederlandse antillen", "netherlands antilles"],
    "de": ["germany", "deutschland", "duitsland", "de", "brd"],
    "be": ["belgium", "belgië", "belgie"],
    "us": ["usa", "us", "united states", "verenigde staten", "united states of america", "u s a", "vs"],
    "gb": ["united kingdom", "gb", "great britain", "groot brittannie", "groot-brittannië", "uk", "u k",
           "verenigd koninkrijk", "grat britain", "united kongdom", "groot brittannië", "england", "scotland", "northern ireland"],
    "ch": ["switzerland", "ch", "zwitserland", "switserland", "swiss", "swizterland"],
    "fr": ["france", "fr", "frankrijk"],
    "es": ["spain", "es", "spanje", "mallorca"],
    "ru": ["russia", "ru", "rusland"],
    "ca": ["canada", "ca", "british columbia"],
    "ne": ["ne"],
    "au": ["australia", "au", "australië", "australie"],
    "it": ["italy", "it", "italie", "italië"],
    "jp": ["japan", "jp"],
    "il": ["israel", "il", "israël"],
    "at": ["austria", "at", "oostenrijk", "austrria"],
    "no": ["norway", "no", "noorwegen"],
    "se": ["sweden", "se", "zweden"],
    "fi": ["finland", "fi"],
    "dk": ["denmark", "dk", "denemarken"],
    "br": ["brazil", "br", "brasil", "brazilie", "brazilië", "brasilia"],
    "pt": ["portugal", "pt"],
    "ie": ["ireland", "ie", "ierland"],
    "pl": ["poland", "pl", "polen"],
    "gr": ["greece", "gr", "griekenland"],
    "za": ["south africa", "za", "zuid afrika", "zuid-afrika"],
    "lu": ["luxembourg", "lu", "luxemburg"],
    "hk": ["hong kong", "hongkong"],
    "ee": ["estonia", "ee", "estland"],
    "mx": ["mexico", "mx"],
    "tr": ["turkey", "tr", "turkiye", "turkije"],
    "lv": ["latvia", "lv", "letland", "lavia", "lativia"],
    "ro": ["romania", "ro"],
    "kr": ["south korea", "kr", "korea", "zuid korea", "republic of korea", "skorea"],
    "sg": ["singapore", "sg"],
    "ua": ["ukraine", "ua"],
    "tw": ["taiwan"],
    "hu": ["hungary", "hu", "hongarije"],
    "nz": ["new zealand", "nz"],
    "lt": ["lithuania", "lt", "litouwen", "lithaunia"],
    "ar": ["argentina", "argentine"],
    "cz": ["czech republic", "cz", "czechia", "cezchia"],
    "cy": ["cyprus"],
    "ve": ["venezuela"],
    "sk": ["slovakia", "sk"],
    "is": ["iceland", "ijsland"],
    "cn": ["china", "china, people's republic of"],
    "kw": ["kuwait"],
    "sa": ["saudi arabia", "saudi arabië", "saudia arabia", "saudi-arabië"],
    "bg": ["bulgaria", "bulgarije", "bulgary"],
    "hr": ["croatia", "kroatië"],
    "in": ["india"],
    "cl": ["chile"],
    "ae": ["united arab emirates", "ae", "uae", "dubai"],
    "lb": ["lebanon", "libanon"],
    "co": ["colombia"],
    "si": ["slovenia", "si", "slovenië"],
    "pa": ["panama"],
    "mt": ["malta"],
    "th": ["thailand"],
    "my": ["malaysia"],
    "by": ["belarus"],
    "am": ["armenia"],
    "ge": ["georgia", "georgië"],
    "id": ["indonesia", "indonesie"],
    "ph": ["philippines", "filipijnen"],
    "rs": ["serbia"],
    "mc": ["monaco"],
    "pe": ["peru"],
    "qa": ["qatar"],
    "pr": ["puerto rico"],
    "al": ["albania"],
    "dz": ["algerije"],
    "eg": ["egypt", "egypte"],
    "uz": ["uzbekistan"],
    "az": ["azerbaijan", "azerbaidzjan"],
    "aw": ["aruba"],
    "sm": ["san marino"],
    "li": ["liechtenstein"],
    "sr": ["surinam", "suriname"],
    "lk": ["sri lanka"],
    "bb": ["barbados"],
    "uy": ["uruguay"],
    "ec": ["ecuador"],
    "kz": ["kazakhstan", "kazachstan", "kazahstan"],
    "ke": ["kenya"],
    "jm": ["jamaica"],
    "kh": ["cambodia"],
    "pk": ["pakistan"],
    "jo": ["jordan"],
    "gh": ["ghana"],
    "ma": ["morocco"],
    "gt": ["guatemala"],
    "cw": ["curacao", "curaçao"],
    "ug": ["uganda"],
    "tt": ["trinidad and tobago"],
    "vg": ["british virgin islands"],
    "bm": ["bermuda"],
    "bz": ["belize"],
    "ir": ["iran"],
    "ba": ["bosnia herzegowina"],
    "as": ["american samoa"],
    "af": ["afghanistan"],
    "ng": ["nigeria"],
    "iq": ["iraq"],
    "md": ["moldavia"],
    "sv": ["el salvador"],
    "zw": ["zimbabwe"],
    "me": ["montenegro"],
    "vi": ["usvi"],
    "mo": ["macau"],
    "hn": ["honduras"],
    "so": ["somalia"],
    "ky": ["cayman islands"],
    "je": ["channel islands"],
    "do": ["dominican republic"],
    "bh": ["bahrain"],
    "na": ["namibia"],
    "mq": ["martinique"],
    "vn": ["vietnam"],
    "bo": ["bolivia"],
    "mk": ["north macedonia", "noord-macedonië"],
    "om": ["oman"],
    "py": ["paraguay"],
}

country_selectio_menu_dict = [
    "nl", "au", "at", "be", "ca", "cz", "dk", "ee", "fi", "fr", "de", "gb", "gr", "hu",
    "ie", "il", "it", "jp", "kr", "lv", "lt", "lu", "mx", "nz", "no", "pl", "pt", "ro",
    "ru", "sg", "sk", "si", "za", "es", "se", "ch", "tr", "ua", "us", "br", "ae"
    ]

flirt_mapping_dict = {
    'flirtxl - messa da requiem': '22/23 messa da requiem flirt',
    'flirt xl - forsythe': '22/23 forsythe flirt',
    '23/24 operaflirt xl - don giovanni': '21/22 don giovanni flirt',
    '18/19 die zauberflote - operaflirt xl': '18/19 die zauberflote flirt',
    '23/24 flirt xl -  die zauberflote': '23/24 die zauberflote flirt',
    '23/24 flirt xl - frida': '23/24 frida flirt',
    '19/20 opera flirt xl cosi fan tutte': '19/20 cosi fan tutte flirt',
    '24/25 don quichot - flirt': '24/25 don quichot flirt' 
}

hh_replace_dict = {
    'nuenen, gerwen en nederwetten': 'nuenen',
    'beek (l.)': 'beek',
    'groningen (gemeente)': 'groningen',
    'hengelo (o.)': 'hengelo',
    'laren (nh.)': 'laren',
    "'s-gravenhage (gemeente)": 'den haag',
    'middelburg (z.)': 'middelburg',
    'rijswijk (zh.)': 'rijswijk',
    'stein (l.)': 'stein',
    'utrecht (gemeente)': 'utrecht'
}